#!/bin/bash

# Setup script to create .env file for Typesense mirror

echo "=== Typesense Mirror Environment Setup ==="
echo "This script will help you create a .env file with your GitHub credentials."
echo ""

# Check if .env already exists
if [ -f ".env" ]; then
    echo "Warning: .env file already exists."
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! $overwrite =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

echo "Please provide your GitHub credentials:"
echo ""

# Get GitHub username
read -p "GitHub Username: " github_username
if [ -z "$github_username" ]; then
    echo "Error: GitHub username is required."
    exit 1
fi

# Get GitHub token
read -s -p "GitHub Personal Access Token: " github_token
echo ""
if [ -z "$github_token" ]; then
    echo "Error: GitHub token is required."
    exit 1
fi

# Get repository name
read -p "GitHub Repository (format: username/repo-name): " github_repo
if [ -z "$github_repo" ]; then
    echo "Error: GitHub repository is required."
    exit 1
fi

# Get Typesense version (optional)
read -p "Typesense Version (default: 29.0): " typesense_version
typesense_version=${typesense_version:-"29.0"}

# Get target tag (optional)
read -p "Target Tag (default: same as version): " target_tag
target_tag=${target_tag:-"$typesense_version"}

# Create .env file
cat > .env << EOF
# GitHub Container Registry Configuration
# Generated by setup_env.sh

# Your GitHub username
GITHUB_USERNAME=$github_username

# Your GitHub Personal Access Token with write:packages permission
GITHUB_TOKEN=$github_token

# GitHub repository name in format username/repo-name
GITHUB_REPO=$github_repo

# Typesense version to mirror
TYPESENSE_VERSION=$typesense_version

# Target tag for GitHub Container Registry
TARGET_TAG=$target_tag
EOF

echo ""
echo "✅ .env file created successfully!"
echo ""
echo "Configuration:"
echo "  GitHub Username: $github_username"
echo "  GitHub Repository: $github_repo"
echo "  Typesense Version: $typesense_version"
echo "  Target Tag: $target_tag"
echo ""
echo "You can now run: ./example_usage.sh"
echo ""
echo "⚠️  Important: Keep your .env file secure and never commit it to version control!" 